name: CI

on: [push, pull_request]

env:
  PYTHON_VERSION: '3.9'

jobs:

  algorithm-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: actions/checkout@v1
      - name: Build the containers
        run: |
          ./build.sh
      - name: Run the tests
        run: |
          ./test.sh
